common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common.views import account_views, profile_views

app_name = 'common'

urlpatterns = [
    # account_views.py
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', account_views.logout_view, name='logout'),
    path('signup/', account_views.signup, name='signup'),

    # profile_views.py
    # 프로필
    path('profile/base/<int:user_id>/', profile_views.profile_base, name='profile_base'),
    path('profile/base/<int:user_id>/edit/', profile_views.profile_edit, name='profile_edit'),
    path('profile/question/<int:user_id>/', profile_views.ProfileQuestionListView.as_view(), name='profile_question'),
    path('profile/answer/<int:user_id>/', profile_views.ProfileAnswerListView.as_view(), name='profile_answer'),
    path('profile/comment/<int:user_id>/', profile_views.ProfileCommentListView.as_view(), name='profile_comment'),
    path('profile/vote/<int:user_id>/', profile_views.ProfileVoteListView.as_view(), name='profile_vote'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from home.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('common/', include('common.urls')),
    path('jobs/', include('jobs.urls')),
    path('reviews/', include('reviews.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

home/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'home'

urlpatterns = [
    # base_views.py
    path('question/list/', base_views.index, name='index'),
    path('question/list/<str:category_name>/', base_views.index, name='index'),
    path('question/detail/<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/<str:category_name>/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),

]

jobs/urls.py
# jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.job_list, name='job_list'),  # '/' 경로로 job_list 뷰를 처리
    path('<int:job_id>/', views.job_detail, name='job_detail'),  # '/' 경로로 job_list 뷰를 처리
    path('<int:job_id>/upload_resume/', views.upload_resume, name='upload_resume'),
    path('company/<int:company_id>/reviews/', views.company_reviews, name='company_reviews'),
]

common/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
from django_countries.fields import CountryField

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    country = CountryField(blank_label='(Select country)', null=True, blank=True)  # 출신 국가
    address = models.CharField(max_length=255, null=True, blank=True)  # 거주지
    birth_date = models.DateField(null=True, blank=True)  # 생년월일
    age = models.PositiveIntegerField(null=True, blank=True)

    def save(self, *args, **kwargs):
        # 생년월일로 나이를 계산
        if self.birth_date:
            today = date.today()
            self.age = (
                    today.year - self.birth_date.year -
                    ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
            )
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username

common/forms.py
from django import forms
from django_countries.fields import CountryField
import django.contrib.auth.forms as auth_forms
from django.contrib.auth.models import User
from .models import UserProfile


class UserForm(auth_forms.UserCreationForm):
    country = CountryField(blank_label='(선택하세요)').formfield()
    address = forms.CharField(max_length=255, required=True, label="현재 주소")
    birth_date = forms.DateField(
        required=True,
        label="생년월일",
        widget=forms.DateInput(attrs={'type': 'date'}) # HTML5 date picker
    )
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email", "country", "address", "birth_date")


# 프로필 수정 폼
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['country', 'address', 'birth_date']  # 수정하고자 하는 필드들

    birth_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),  # date input 위젯
        required=True
    )


common/views/account_views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from common.forms import UserForm
from common.models import UserProfile

# 회원가입
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            # 기본 User 모델에 사용자 저장
            user = form.save()
            #form.save()

            # UserProfile 모델에 추가 정보 저장
            country = form.cleaned_data.get('country') # 출신 국가 저장
            address = form.cleaned_data.get('address') # 현재 거주지 저장
            birth_date = form.cleaned_data.get('birth_date') # 생년월일

            UserProfile.objects.create(user=user, country=country, address=address, birth_date=birth_date)

            # 사용자 인증 후 로그인
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인

            return redirect('home:index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

# 로그아웃
def logout_view(request):
    logout(request)
    return redirect('index')



common/views/profile_views.py
from itertools import chain
from django.contrib.auth.decorators import login_required
from django.db.models import F, Count
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView

from home.models import Question, Answer, Comment
from common.forms import UserForm, UserProfileForm
from common.models import UserProfile

# 프로필 기본정보
def profile_base(request, user_id):
    profile_user = get_object_or_404(User, pk=user_id)
    user_profile = profile_user.profile  # UserProfile 객체

    context = {
        'profile_user': profile_user,
        'user_profile': user_profile,
        'profile_type': 'base'
    }
    return render(request, 'common/profile/profile_base.html', context)


# 프로필 목록 추상 클래스 뷰
class ProfileObjectListView(ListView):
    paginate_by = 10

    class Meta:
        abstract = True

    def get_queryset(self):
        self.profile_user = get_object_or_404(User, pk=self.kwargs['user_id'])
        self.so = self.request.GET.get('so', 'recent')  # 정렬기준
        object_list = self.model.objects.filter(author=self.profile_user)
        # 정렬
        object_list = Answer.order_by_so(object_list, self.so)
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'profile_user': self.profile_user,
            'profile_type': self.profile_type,
            'so': self.so
        })
        return context


# 작성한 질문 목록
class ProfileQuestionListView(ProfileObjectListView):
    model = Question
    template_name = 'common/profile/profile_question.html'
    profile_type = 'question'


# 작성한 답변 목록
class ProfileAnswerListView(ProfileObjectListView):
    model = Answer
    template_name = 'common/profile/profile_answer.html'
    profile_type = 'answer'


# 작성한 댓글 목록
class ProfileCommentListView(ProfileObjectListView):
    model = Comment
    template_name = 'common/profile/profile_comment.html'
    profile_type = 'comment'


# 추천 목록
class ProfileVoteListView(ProfileObjectListView):
    template_name = 'common/profile/profile_vote.html'
    profile_type = 'vote'

    def get_queryset(self):
        self.profile_user = get_object_or_404(User, pk=self.kwargs['user_id'])

        # 질문과 답변을 결합한 쿼리셋
        question_list = self.profile_user.voter_question.all()
        answer_list = self.profile_user.voter_answer.annotate(category=F('question__category__description'))
        combined_list = chain(question_list, answer_list)

        # 정렬 기준 적용
        so = self.request.GET.get('so', 'recent')
        if so == 'recommend':
            sorted_list = sorted(
                combined_list,
                key=lambda obj: getattr(obj, 'voter_count', 0),
                reverse=True,
            )
        else:
            sorted_list = sorted(
                combined_list,
                key=lambda obj: obj.create_date,
                reverse=True,
            )
        return sorted_list


    def get_context_data(self, **kwargs):
        context = ListView.get_context_data(self, **kwargs)
        context.update({
            'profile_user': self.profile_user,
            'profile_type': self.profile_type,
            'so': self.request.GET.get('so', 'recent')
        })
        return context


@login_required
def profile_edit(request, user_id):
    # 프로필 정보를 가져오는 코드
    profile_user = get_object_or_404(UserProfile, user__id=user_id)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=profile_user)
        if form.is_valid():
            form.save()
            # 수정 후 profile_base로 리디렉션할 때 user_id 전달
            return redirect('common:profile_base', user_id=user_id)
    else:
        form = UserProfileForm(instance=profile_user)

    return render(request, 'common/profile/profile_edit.html', {'form': form})

nextbridge/common/views/profile_views.py
from itertools import chain
from django.contrib.auth.decorators import login_required
from django.db.models import F, Count
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView

from home.models import Question, Answer, Comment
from common.forms import UserForm, UserProfileForm
from common.models import UserProfile

# 프로필 기본정보
def profile_base(request, user_id):
    profile_user = get_object_or_404(User, pk=user_id)
    user_profile = profile_user.profile  # UserProfile 객체

    context = {
        'profile_user': profile_user,
        'user_profile': user_profile,
        'profile_type': 'base'
    }
    return render(request, 'common/profile/profile_base.html', context)


# 프로필 목록 추상 클래스 뷰
class ProfileObjectListView(ListView):
    paginate_by = 10

    class Meta:
        abstract = True

    def get_queryset(self):
        self.profile_user = get_object_or_404(User, pk=self.kwargs['user_id'])
        self.so = self.request.GET.get('so', 'recent')  # 정렬기준
        object_list = self.model.objects.filter(author=self.profile_user)
        # 정렬
        object_list = Answer.order_by_so(object_list, self.so)
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'profile_user': self.profile_user,
            'profile_type': self.profile_type,
            'so': self.so
        })
        return context


# 작성한 질문 목록
class ProfileQuestionListView(ProfileObjectListView):
    model = Question
    template_name = 'common/profile/profile_question.html'
    profile_type = 'question'


# 작성한 답변 목록
class ProfileAnswerListView(ProfileObjectListView):
    model = Answer
    template_name = 'common/profile/profile_answer.html'
    profile_type = 'answer'


# 작성한 댓글 목록
class ProfileCommentListView(ProfileObjectListView):
    model = Comment
    template_name = 'common/profile/profile_comment.html'
    profile_type = 'comment'


# 추천 목록
class ProfileVoteListView(ProfileObjectListView):
    template_name = 'common/profile/profile_vote.html'
    profile_type = 'vote'

    def get_queryset(self):
        self.profile_user = get_object_or_404(User, pk=self.kwargs['user_id'])
        question_list = self.profile_user.voter_question.all()
        answer_list = self.profile_user.voter_answer.annotate(category=F('question__category__description'))

        _queryset = sorted(
            chain(question_list, answer_list),
            key=lambda obj: obj.create_date,
            reverse=True,
        )
        return _queryset

    def get_context_data(self, **kwargs):
        context = ListView.get_context_data(self, **kwargs)
        context.update({
            'profile_user': self.profile_user,
            'profile_type': self.profile_type,
            # 'so': self.so
        })
        return context


@login_required
def profile_edit(request, user_id):
    # 프로필 정보를 가져오는 코드
    profile_user = get_object_or_404(UserProfile, user__id=user_id)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=profile_user)
        if form.is_valid():
            form.save()
            # 수정 후 profile_base로 리디렉션할 때 user_id 전달
            return redirect('common:profile_base', user_id=user_id)
    else:
        form = UserProfileForm(instance=profile_user)

    return render(request, 'common/profile/profile_edit.html', {'form': form})

nextbridge/templates/common/profile/profile_answer.html
{% extends "base.html" %}
{% load home_filter %}

{% block content %}
<h4 class="border-bottom pb-2 my-3">{{ profile_user.username }}</h4>
{% include "common/profile/profile_tabs.html" %}

<!-- 답변 표시 Start -->
<select class="form-control so my-3">
    <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
    <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
</select>

<table class="table">
    <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>구분</th>
            <th>추천</th>
            <th style="width:50%">내용</th>
            <th>작성일시</th>
        </tr>
    </thead>
    <tbody>
    {% if page_obj %}
    {% for object in page_obj %}
    <tr class="text-center">
        <td>
            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
            {{ page_obj.paginator.count|sub:page_obj.start_index|sub:forloop.counter0|add:1 }}
        </td>
        <td>{{ object.question.category.description }}</td>  {# 수정함 #}
        <td>
            {% if object.voter.count > 0 %}
                <span class="badge badge-warning px-2 py-1">{{ object.voter.count }}</span>
            {% else %}
                <span class="badge badge-light px-2 py-1" style="color:#ccc;">0</span>
            {% endif %}
        </td>
        <td class="text-left">
            <a href="{{ object.get_absolute_url }}">{{ object }}</a>
{#            {% if object.answer_set.count > 0 %}#}
{#                <span class="text-danger small ml-2">{{ object.answer_set.count }}</span>#}
{#            {% endif %}#}
        </td>
        <td>{{ object.create_date }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">등록한 답변이 없습니다.</td>
    </tr>
    {% endif %}
    </tbody>
</table>

<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="1" href="#">처음</a>
        </li>
       <li class="page-item">
            <a class="page-link" data-page="{{ page_obj.previous_page_number }}" href="#">이전</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">처음</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in page_obj.paginator.page_range %}
        {% if page_number >= page_obj.number|add:-4 and page_number <= page_obj.number|add:4 %}
            {% if page_number == page_obj.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if page_obj.has_next %}
        <li class="page-item">
             <a class="page-link" data-page="{{ page_obj.next_page_number }}" href="#">다음</a>
        </li>
        <li class="page-item">
             <a class="page-link" data-page="{{ page_obj.paginator.num_pages }}" href="#">끝</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">끝</a>
        </li>
    {% endif %}
</ul>
<!-- 페이징처리 끝 -->

<form id="searchForm" method="get">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
    $(document).ready(function(){
        $(".page-link").on('click', function() {
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });
        $(".so").on('change', function() {
            $("#so").val($(this).val());
            $("#page").val(1);  // 새로운 기준으로 정렬할 경우 1페이지부터 조회한다.
            $("#searchForm").submit();
        });
    });
</script>
{% endblock %}

nextbridge/templates/common/profile/profile_base.html
{% extends "base.html" %}

{% block content %}
<div class="container my-5">
    <h4 class="border-bottom pb-2 my-3 text-center">{{ profile_user.username }}님의 프로필</h4>
    {% include "common/profile/profile_tabs.html" %}

    <div id="profile_base">

        <div class="card">
            <div class="card-header bg-primary text-white text-center">
                <h5 class="mb-0">프로필 정보</h5>
            </div>
            <div class="card-body">
                <!-- 이메일 -->
                <div class="mb-3">
                    <h5 class="card-title">이메일</h5>
                    <p class="card-text">{{ profile_user.email }}</p>
                </div>

                <!-- 출신 국가 -->
                <div class="mb-3">
                    <h5 class="card-title">출신 국가</h5>
                    <p class="card-text">
                        <span class="fi fi-gr fis-{{ user_profile.country.code|lower }}"></span>
                        {{ user_profile.country.name }}
                    </p>
                </div>

                <!-- 현재 거주지 -->
                <div class="mb-3">
                    <h5 class="card-title">현재 거주지</h5>
                    <p class="card-text">{{ user_profile.address }}</p>
                </div>

                <!-- 생년월일 (나이 자동 계산) -->
                <div class="mb-3">
                    <h5 class="card-title">생년월일</h5>
                    <p class="card-text">{{ user_profile.birth_date }}</p>
                </div>
            </div>
            {% if user == profile_user %}
            <div class="card-footer text-center">
                <a href="{% url 'common:profile_edit' user_id=profile_user.id %}" class="btn btn-warning">프로필 수정</a>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

nextbridge/templates/common/profile/profile_comment.html
{% extends "base.html" %}
{% load home_filter %}

{% block content %}
<h4 class="border-bottom pb-2 my-3">{{ profile_user.username }}</h4>
{% include "common/profile/profile_tabs.html" %}

<!-- 답변 표시 Start -->
<select class="form-control so my-3">
    <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
    <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
</select>

<table class="table">
    <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>구분</th>
{#            <th>추천</th>#}
            <th style="width:50%">내용</th>
            <th>작성일시</th>
        </tr>
    </thead>
    <tbody>
    {% if page_obj %}
    {% for object in page_obj %}
    <tr class="text-center">
        <td>
            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
            {{ page_obj.paginator.count|sub:page_obj.start_index|sub:forloop.counter0|add:1 }}
        </td>
        <td>
            {% if object.question %}
                {{ object.question.category.description }}{#| 질문#}
            {% else %}
                {{ object.answer.question.category.description }}{#| 답변#}
            {% endif %}
        </td>
{#        <td>#}
{#            {% if object.voter.count > 0 %}#}
{#                <span class="badge badge-warning px-2 py-1">{{ object.voter.count }}</span>#}
{#            {% else %}#}
{#                <span class="badge badge-light px-2 py-1" style="color:#ccc;">0</span>#}
{#            {% endif %}#}
{#        </td>#}
        <td class="text-left">
            <a href="{{ object.get_absolute_url }}">{{ object }}</a>
        </td>
        <td>{{ object.create_date }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">등록한 댓글이 없습니다.</td>
    </tr>
    {% endif %}
    </tbody>
</table>

<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="1" href="#">처음</a>
        </li>
       <li class="page-item">
            <a class="page-link" data-page="{{ page_obj.previous_page_number }}" href="#">이전</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">처음</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in page_obj.paginator.page_range %}
        {% if page_number >= page_obj.number|add:-4 and page_number <= page_obj.number|add:4 %}
            {% if page_number == page_obj.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if page_obj.has_next %}
        <li class="page-item">
             <a class="page-link" data-page="{{ page_obj.next_page_number }}" href="#">다음</a>
        </li>
        <li class="page-item">
             <a class="page-link" data-page="{{ page_obj.paginator.num_pages }}" href="#">끝</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">끝</a>
        </li>
    {% endif %}
</ul>
<!-- 페이징처리 끝 -->

<form id="searchForm" method="get">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
    $(document).ready(function(){
        $(".page-link").on('click', function() {
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });
        $(".so").on('change', function() {
            $("#so").val($(this).val());
            $("#page").val(1);  // 새로운 기준으로 정렬할 경우 1페이지부터 조회한다.
            $("#searchForm").submit();
        });
    });
</script>
{% endblock %}

nextbridge/templates/common/profile/profile_edit.html
{% extends "base.html" %}

{% block content %}
<h4 class="border-bottom pb-2 my-3">{{ profile_user.username }}의 프로필 수정</h4>
<form method="post">
    {% csrf_token %}

    <!-- 국가 필드 -->
    <div class="mb-3">
        <label for="id_country">출신 국가</label>
        <select name="country" class="form-control" id="id_country">
            {% for country in form.country.field.choices %}
                <option value="{{ country.0 }}" {% if form.country.value == country.0 %}selected{% endif %}>
                    {{ country.1 }}
                </option>
            {% endfor %}
        </select>
    </div>

    <!-- 주소 필드 -->
    <div class="mb-3">
        <label for="id_address">주소</label>
        <input type="text" name="address" class="form-control" id="id_address"
               value="{{ form.address.value }}">
    </div>

    <!-- 생년월일 필드 -->
    <div class="mb-3">
        <label for="id_birth_date">생년월일</label>
        <input type="date" name="birth_date" class="form-control" id="id_birth_date"
               value="{{ form.birth_date.value|date:'Y-m-d' }}">
    </div>

    <!-- 기타 필드 (이메일 등) -->

    <button type="submit" class="btn btn-primary">수정하기</button>
</form>
{% endblock %}

nextbridge/templates/common/profile/profile_tabs.html
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'base' %}active{% endif %}" href="{% url 'common:profile_base' profile_user.id %}">기본정보</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'question' %}active{% endif %}" href="{% url 'common:profile_question' profile_user.id %}">게시</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'answer' %}active{% endif %}" href="{% url 'common:profile_answer' profile_user.id %}">답변</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'comment' %}active{% endif %}" href="{% url 'common:profile_comment' profile_user.id %}">댓글</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'vote' %}active{% endif %}" href="{% url 'common:profile_vote' profile_user.id %}">추천</a>
    </li>
</ul>