common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common.views import account_views, profile_views

app_name = 'common'

urlpatterns = [
    # account_views.py
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', account_views.logout_view, name='logout'),
    path('signup/', account_views.signup, name='signup'),

    # profile_views.py
    # 프로필
    path('profile/base/<int:user_id>/', profile_views.profile_base, name='profile_base'),
    path('profile/base/<int:user_id>/edit/', profile_views.profile_edit, name='profile_edit'),
    path('profile/question/<int:user_id>/', profile_views.ProfileQuestionListView.as_view(), name='profile_question'),
    path('profile/answer/<int:user_id>/', profile_views.ProfileAnswerListView.as_view(), name='profile_answer'),
    path('profile/comment/<int:user_id>/', profile_views.ProfileCommentListView.as_view(), name='profile_comment'),
    path('profile/vote/<int:user_id>/', profile_views.ProfileVoteListView.as_view(), name='profile_vote'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from home.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('common/', include('common.urls')),
    path('jobs/', include('jobs.urls')),
    path('reviews/', include('reviews.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

home/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'home'

urlpatterns = [
    # base_views.py
    path('question/list/', base_views.index, name='index'),
    path('question/list/<str:category_name>/', base_views.index, name='index'),
    path('question/detail/<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/<str:category_name>/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),

]

jobs/urls.py
# jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.job_list, name='job_list'),  # '/' 경로로 job_list 뷰를 처리
    path('<int:job_id>/', views.job_detail, name='job_detail'),  # '/' 경로로 job_list 뷰를 처리
    path('<int:job_id>/upload_resume/', views.upload_resume, name='upload_resume'),
    path('company/<int:company_id>/reviews/', views.company_reviews, name='company_reviews'),
]

reviews/urls.py
from django.urls import path
from reviews.views import base_views, review_views

app_name = 'reviews'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('list/', base_views.review_list, name='review_list'),
    path('list/<int:review_id>/', base_views.review_detail, name='review_detail'),
    path('company/<int:company_id>/', base_views.company_reviews, name='company_reviews'), # 회사 리뷰 목록
    path('autocomplete/', base_views.company_autocomplete, name='company_autocomplete'), # (리뷰 작성에서) 회사 검색
    path('company_search/', base_views.company_search, name='company_search'),  # (메인화면에서) 회사 검색_검색 API 추가


    # review_views.py
    path('create/', review_views.review_create, name='review_create'),
    path('modify/<int:review_id>/', review_views.review_modify, name='review_modify'),
    path('delete/<int:review_id>/', review_views.review_delete, name='review_delete'),
    path('vote/<int:review_id>/', review_views.review_vote, name='review_vote'),

]

home/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q, Count, Avg
from django.shortcuts import render, get_object_or_404

from ..models import Question, Answer, Category
from jobs.models import JobPosting

# home 목록 출력
def index(request, category_name='community'):
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent') # 정렬기준

    # 회사 정렬
    company_list = JobPosting.objects.all()

    category = get_object_or_404(Category, name=category_name)
    # 정렬
    question_list = Question.order_by_so(
        Question.objects.filter(category=category).select_related('author__profile'), so)

    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()

    # 회사 평점 순으로 정렬
    company_list = JobPosting.objects.annotate(
        review_count=Count('company_reviews'),  # 리뷰 개수 계산
        average_rating=Avg('company_reviews__rating')  # 평균 평점 계산
    ).order_by('-average_rating')[:10]

    # 페이징 처리
    paginator = Paginator(question_list, 15) # 페이지 당 15개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {
        'question_list': page_obj,
        'page': page,
        'kw': kw,
        'so': so,
        'category': category,
        'companies': company_list,
    }
    return render(request, 'home/question_list.html', context)

# 질문 상세
def detail(request, question_id):
    # 입력파라미터
    page = request.GET.get('page', '1')  # 페이지
    so = request.GET.get('so', 'recommend')  # 정렬기준
    question = get_object_or_404(Question, pk=question_id)

    answer_list = Answer.order_by_so(Answer.objects.filter(question=question), so)

    # 페이징 처리
    paginater = Paginator(answer_list, 5) # 페이지당 5개씩 보여주기
    page_obj = paginater.get_page(page)

    context = {'question': question, 'answer_set': page_obj, 'page': page, 'so': so, 'category': question.category}
    return render(request, 'home/question_detail.html', context)

reviews/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.db.models import Q, Count, Avg

from reviews.models import Review
from jobs.models import JobPosting

def index(request):
    # 검색어가 있을 경우 해당 회사들 가져오기
    rw = request.GET.get('rw','') # 검색어가 있으면 rw에 저장
    company_list = JobPosting.objects.all()
    if rw:
        company_list = JobPosting.objects.filter(
            Q(company_name__icontains=rw)
        )

        # 검색된 회사들에 대해서도 리뷰 개수와 평균 평점 계산
        company_list = company_list.annotate(
            review_count=Count('company_reviews'),  # 리뷰 개수 계산
            average_rating=Avg('company_reviews__rating')  # 평균 평점 계산
        )
    else:
        # 리뷰가 많은 순으로 9개 회사 가져오기
        company_list = JobPosting.objects.annotate(
            review_count=Count('company_reviews'),  # 리뷰 개수 계산
            average_rating=Avg('company_reviews__rating')  # 평균 평점 계산
        ).order_by('-review_count')[:9]  # 리뷰 개수가 많은 순으로 정렬

    # 최신 3개의 리뷰를 가져옵니다.
    latest_reviews = Review.objects.order_by('-create_date')[:3]

    context = {
        'latest_reviews': latest_reviews, # 최신 리뷰
        'companies': company_list, # 검색된 회사들
        'range': range(1, 6),
        'rw': rw,
    }
    # 최신 리뷰를 템플릿으로 전달
    return render(request, 'reviews/review_main.html', context)

def review_list(request):
    review_list = Review.objects.order_by('-create_date')
    context = {
        'review_list': review_list,
        'range': range(1, 6),  # 1부터 5까지 반복
    }
    return render(request, 'reviews/review_list.html', context)


# 리뷰 상세보기
def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    context = {
        'review': review,
        'range': range(1, 6),  # 1부터 5까지 반복
    }
    return render(request, 'reviews/review_detail.html', context)


# 회사 별 리뷰보기
def company_reviews(request, company_id):
    # 회사 정보 가져오기
    company = get_object_or_404(JobPosting, pk=company_id)

    # 해당 회사의 리뷰 필터링
    kw = request.GET.get('kw', '')   # 검색어
    # 해당 회사에 대한 리뷰 조회
    company_review_list = Review.objects.filter(company=company).order_by('-create_date')

    # 해당 회사의 채용공고 조회
    jobs = JobPosting.objects.filter(company_name=company.company_name)

    if kw:
        company_review_list = company_review_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(comment__icontains=kw) |  # 내용 검색
            Q(author__username__icontains=kw)   # 질문 글쓴이 검색
        ).distinct()

    context = {
        'company' : company,
        'reviews' : company_review_list,
        'kw' : kw,
        'jobs': jobs
    }
    return render(request, 'reviews/company_reviews.html', context)


# (리뷰 입력에서) 회사 검색
def company_autocomplete(request):
    query = request.GET.get('query', '').strip()
    if query:
        companies = JobPosting.objects.filter(company_name__icontains=query)[:10]
        data = {'companies': [{'company_name': company.company_name} for company in companies]}
    else:
        data = {'companies': []}
    return JsonResponse(data)


# (메인페이지에서) 회사 검색
def company_search(request):
    query = request.GET.get('q', '')
    if query:
        companies = JobPosting.objects.filter(name__icontains=query)[:10]  # 최대 10개
        results = [{'id': company.id, 'name': company.name} for company in companies]
        return JsonResponse(results, safe=False)
    return JsonResponse([], safe=False)


templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- 폰트 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Gamja+Flower&family=Gowun+Dodum&family=Jua&family=Poor+Story&display=swap" rel="stylesheet">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- home CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- 국기와 함께 국가 선택 -->
    <!-- flag-icon-css 스타일 추가 -->
    <link rel="stylesheet"  href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@7.2.3/css/flag-icons.min.css"/>
    <!-- favicon.ico 추가 (optional) -->
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>NextBridge</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<div class="container my-3">
    <div class="row">
        <!-- Sidebar: /home 경로에서만 표시 -->
        {% if "/home" in request.path %}
        <div class="col-sm-12 col-md-3 col-lg-2 p-2">
            {% include "sidebar.html" %}
        </div>
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
</div>
<!-- 기본 템플릿 안에 삽입될 내용 End -->


<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트(삭제) Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    <!-- 사용자가 입력한 필드 값에 대한 요류. 값이 누락되었거나 필드의 형식이 일치하지 않는 경우 발생 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    <!-- 필드의 값과는 상관없이 다른 이유로 발생하는 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
{% load static %}  <!-- static 태그 로드 -->

<!-- 폰트 -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Gamja+Flower&family=Gowun+Dodum&family=Jua&family=Poor+Story&display=swap" rel="stylesheet">


<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 'home:index' %}">
            <img src="{% static 'img/logo_img.png' %}" alt="로고 이미지" style="width: 150px; height: auto;">
        </a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">홈</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'jobs:job_list' %}">채용 공고</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reviews:index' %}">회사 리뷰</a>
                </li>
                <!-- 로그인 or 로그아웃-->

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:profile_base' user.id %}">{{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                </li>
                {% else %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                </li>
                {% endif %}


            </ul>
        </div>


    </div>
</nav>

templates/sidebar.html
<!-- Sidebar  -->
<nav id="sidebar" class="border-top border-secondary">
    <div class="list-group">
            <a class="rounded-0 list-group-item list-group-item-action list-group-item-light
               {% if category.name == 'community' %}active{% endif %}" href="{% url 'home:index' 'community' %}">커뮤니티</a>
    </div>
</nav>